"""Kestra task — Process faixa etária Excel files and append to Google Sheets.

Reads Excel files generated by kestra_faixa.py, extracts data tables,
and appends new rows to the target Google Sheets tab.

Each row is prefixed with source metadata (US, Tipo, Ano, Semana) parsed
from the filename, so aggregates from different units/weeks stay traceable.
Dedup is by row hash (metadata + all data columns) since faixa etária tables
are aggregates with no unique ID.

Env in:
  GOOGLE_SERVICE_ACCOUNT  -> service-account JSON (string)
  SHEET_ID                -> spreadsheet id (from its URL)
  SHEET_TAB               -> worksheet/tab name (e.g. 'SG-agregados')
  FAIXA_PATTERN           -> filter Excel files by name (e.g. 'SG_' or 'SRAG_UTI_')
"""

import json
import os
import re
import sys
from pathlib import Path

import gspread
import pandas as pd

# Source-metadata columns prepended to every aggregate row.
META_COLS = ["US", "Tipo", "Ano", "Semana", "Arquivo"]
# "Arquivo" carries a per-run id, so it's provenance only — excluded from the
# dedup key so re-runs of the same US/week don't append duplicate rows.
_ARQUIVO_IDX = META_COLS.index("Arquivo")


def _dedup_key(row) -> int:
    """Hash a row for dedup, ignoring the run-specific 'Arquivo' column."""
    return hash(tuple(str(v) for i, v in enumerate(row) if i != _ARQUIVO_IDX))

# faixaetaria_US153_SG_2026_se23_<runid>_<suggested>.xls
#            └─US─┘ └tipo┘ └ano┘ └sem┘
_NAME_RE = re.compile(
    r"faixaetaria_US(?P<us>\d+)_(?P<tipo>.+?)_(?P<ano>\d{4})_se(?P<sem>\d+)_",
    re.IGNORECASE,
)


def parse_meta(filename: str) -> dict:
    """Extract (US, Tipo, Ano, Semana) from a faixa etária filename."""
    m = _NAME_RE.search(filename)
    if not m:
        return {"us": "", "tipo": "", "ano": "", "sem": ""}
    return m.groupdict()


def read_excel_rows(path: Path) -> tuple[list, list[tuple]]:
    """Read header + data rows of a SIVEP 'Excel' export.

    The portal may serve real .xlsx, legacy binary .xls, or an HTML table with an
    .xls filename — try pandas' Excel engines first, then fall back to read_html.
    Returns (header, rows).
    """
    try:
        df = pd.read_excel(path, header=0)
    except Exception:
        df = pd.read_html(path, header=0)[0]
    df = df.where(pd.notna(df), None)  # NaN -> None so blank cells become ""
    header = [str(c) for c in df.columns]
    rows = [tuple(r) for r in df.itertuples(index=False, name=None)]
    return header, rows


def push_faixa_to_sheets(
    *,
    pattern: str,
    sheet_tab: str,
    sheet_id: str,
    service_account_json: str,
    downloads_dir: Path | None = None,
    log=print,
) -> int:
    """Read matching faixa etária Excel files and append new rows to the sheet.

    Returns the number of new rows appended (0 if all duplicates / no files).
    Raises on connection or auth errors.
    """
    downloads_dir = downloads_dir or (Path(__file__).parent.parent / "downloads")
    excel_files = list(downloads_dir.glob(f"faixaetaria*{pattern}*.xls*"))

    if not excel_files:
        log(
            f"Nenhum arquivo encontrado em {downloads_dir} com padrão "
            f"'faixaetaria*{pattern}*.xls*'"
        )
        return 0

    log(f"Encontrados {len(excel_files)} arquivo(s) com padrão '{pattern}'")

    # Read and consolidate all Excel files, prefixing each row with its source.
    data_header: list[str] = []
    all_rows: list[list] = []
    for excel_file in excel_files:
        log(f"  Lendo {excel_file.name}...")
        meta = parse_meta(excel_file.name)
        try:
            header, rows = read_excel_rows(excel_file)
            if not data_header and header:
                data_header = header
            kept = 0
            for r in rows:
                if not any(v is not None for v in r):
                    continue
                prefixed = [
                    meta["us"], meta["tipo"], meta["ano"], meta["sem"], excel_file.name,
                    *[("" if v is None else v) for v in r],
                ]
                all_rows.append(prefixed)
                kept += 1
            log(f"    → {kept} linhas (US {meta['us']}, semana {meta['sem']})")
        except Exception as e:
            log(f"    ERRO: {e}")
            continue

    if not all_rows:
        log("Nenhuma linha para processar.")
        return 0

    # Connect to Google Sheets.
    creds = json.loads(service_account_json)
    gc = gspread.service_account_from_dict(creds)
    sh = gc.open_by_key(sheet_id)
    try:
        ws = sh.worksheet(sheet_tab)
    except gspread.WorksheetNotFound:
        ncols = len(META_COLS) + len(data_header or all_rows[0][len(META_COLS):])
        ws = sh.add_worksheet(title=sheet_tab, rows=1, cols=max(ncols, 20))

    # Dedup by metadata + data (excluding the run-specific 'Arquivo' column),
    # so re-running the same US/week stays idempotent. Aggregates have no unique ID.
    existing = ws.get_all_values()
    has_header = bool(existing) and existing[0][:len(META_COLS)] == META_COLS
    existing_hashes = (
        {_dedup_key(row) for row in existing[1:]} if has_header else set()
    )

    new_rows = []
    for row in all_rows:
        as_str = [str(v) for v in row]
        h = _dedup_key(as_str)
        if h not in existing_hashes:
            new_rows.append(as_str)
            existing_hashes.add(h)

    # Write header on first use.
    if not has_header:
        header = META_COLS + (data_header or [f"Col_{i}" for i in range(len(all_rows[0]) - len(META_COLS))])
        ws.update([header], "A1")

    if new_rows:
        ws.append_rows(new_rows, value_input_option="RAW")
        log(f"✓ Anexadas {len(new_rows)} linhas ao Google Sheets (aba '{sheet_tab}')")
    else:
        log("Nenhuma linha nova para anexar (todas duplicadas).")

    return len(new_rows)


def main() -> int:
    pattern = os.environ.get("FAIXA_PATTERN", "")
    sheet_id = os.environ.get("SHEET_ID", "")
    sheet_tab = os.environ.get("SHEET_TAB", "")
    service_account_json = os.environ.get("GOOGLE_SERVICE_ACCOUNT", "")

    if not all([pattern, sheet_id, sheet_tab, service_account_json]):
        print("Erro: variáveis de ambiente obrigatórias não definidas.", file=sys.stderr)
        return 1

    try:
        push_faixa_to_sheets(
            pattern=pattern,
            sheet_tab=sheet_tab,
            sheet_id=sheet_id,
            service_account_json=service_account_json,
        )
    except Exception as e:
        print(f"Erro ao enviar ao Google Sheets: {e}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
