"""Kestra task — Process faixa etária Excel files and append to Google Sheets.

Reads Excel files generated by kestra_faixa.py, extracts data tables,
and appends new rows to the target Google Sheets tab.

Dedup is by row hash (all columns) since faixa etária tables are
aggregates with no unique ID.

Env in:
  GOOGLE_SERVICE_ACCOUNT  -> service-account JSON (string)
  SHEET_ID                -> spreadsheet id (from its URL)
  SHEET_TAB               -> worksheet/tab name (e.g. 'SG-agregados')
  FAIXA_PATTERN           -> filter Excel files by name (e.g. 'SG_' or 'SRAG_UTI_')
"""

import glob
import json
import os
import sys
from pathlib import Path

import gspread
import pandas as pd


def read_excel_rows(path: Path) -> list[tuple]:
    """Read the data rows (header skipped) of a SIVEP 'Excel' export.

    The portal may serve real .xlsx, legacy binary .xls, or an HTML table with an
    .xls filename — try pandas' Excel engines first, then fall back to read_html.
    """
    try:
        df = pd.read_excel(path, header=0)
    except Exception:
        df = pd.read_html(path, header=0)[0]
    df = df.where(pd.notna(df), None)  # NaN -> None so blank cells become ""
    return [tuple(r) for r in df.itertuples(index=False, name=None)]


def main() -> int:
    pattern = os.environ.get("FAIXA_PATTERN", "")
    sheet_id = os.environ.get("SHEET_ID", "")
    sheet_tab = os.environ.get("SHEET_TAB", "")
    service_account_json = os.environ.get("GOOGLE_SERVICE_ACCOUNT", "")

    if not all([pattern, sheet_id, sheet_tab, service_account_json]):
        print("Erro: variáveis de ambiente obrigatórias não definidas.", file=sys.stderr)
        return 1

    # Find Excel files in downloads/ matching the pattern (.xls or .xlsx)
    downloads_dir = Path(__file__).parent.parent / "downloads"
    excel_files = list(downloads_dir.glob(f"faixaetaria*{pattern}*.xls*"))

    if not excel_files:
        print(
            f"Nenhum arquivo encontrado em {downloads_dir} com padrão "
            f"'faixaetaria*{pattern}*.xls*'",
            file=sys.stderr,
        )
        return 1

    print(f"Encontrados {len(excel_files)} arquivo(s) com padrão '{pattern}'")

    # Read and consolidate all Excel files (skip header rows)
    all_rows = []
    for excel_file in excel_files:
        print(f"  Lendo {excel_file.name}...")
        try:
            rows = [r for r in read_excel_rows(excel_file) if any(v is not None for v in r)]
            all_rows.extend(rows)
            print(f"    → {len(rows)} linhas")
        except Exception as e:
            print(f"    ERRO: {e}", file=sys.stderr)
            continue

    if not all_rows:
        print("Nenhuma linha para processar.", file=sys.stderr)
        return 1

    # Connect to Google Sheets
    try:
        creds = json.loads(service_account_json)
        gc = gspread.service_account_from_dict(creds)
        sh = gc.open_by_key(sheet_id)
        ws = sh.worksheet(sheet_tab)
    except gspread.WorksheetNotFound:
        # Create tab if doesn't exist
        ws = sh.add_worksheet(title=sheet_tab, rows=1, cols=20)
    except Exception as e:
        print(f"Erro ao conectar ao Google Sheets: {e}", file=sys.stderr)
        return 1

    # Dedup by row hash (all columns) — faixa etária tables are aggregates
    existing = ws.get_all_values()
    existing_hashes = {hash(tuple(row)) for row in existing[1:]} if len(existing) > 1 else set()

    # Filter new rows
    new_rows = []
    for row in all_rows:
        row_hash = hash(tuple(row))
        if row_hash not in existing_hashes:
            new_rows.append([str(v) if v is not None else "" for v in row])
            existing_hashes.add(row_hash)

    # Write header on first use
    if not existing or (len(existing) == 1 and not existing[0]):
        # Assume first row of data has the column names, or use generic names
        header = [f"Col_{i}" for i in range(len(all_rows[0]))]
        ws.update([header], "A1")

    # Append new rows
    if new_rows:
        ws.append_rows(new_rows, value_input_option="RAW")
        print(f"✓ Anexadas {len(new_rows)} linhas ao Google Sheets (aba '{sheet_tab}')")
    else:
        print(f"Nenhuma linha nova para anexar (todas duplicadas).")

    return 0


if __name__ == "__main__":
    sys.exit(main())
